GET http://localhost:3000/places?text=av beira mar, florianopolis, sc


### 

GET http://localhost:3000/places?text=av beira mar, itapema, sc


### 

@originId = ChIJc_sdWhE4J5UR_RyxJl9zrqM
@destinationId = ChIJY6Jvhbux2JQRTjat3ClAocg

###
GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}


###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
POST http://localhost:3000/routes/67596c02396abb18d0c69574/start

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/674ef78bab1148ea9161c23b 
